spring:
  application:
    name: mall-admin
  profiles:
    active: dev #默認為開發環境
  servlet:
    multipart:
      enabled: true #開啟文件上傳
      max-file-size: 10MB #限制文件上傳大小為10M

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存儲的請求頭
  secret: mall-admin-secret #JWT加解密使用的密鑰
  expiration: 604800 #JWT的超期限時間(60*60*24*7)
  tokenHead: 'Bearer '  #JWT負載中拿到開頭

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小時

secure:
  ignored:
    urls: #安全路徑白名單
      
      #- /static/**
      #- /index.html
      
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss對外服務的訪問域名
    accessKeyId: test # 訪問身份驗證中用到用戶標識
    accessKeySecret: test # 用戶用於加密簽名字符串和oss用來驗證簽名字符串的密鑰
    bucketName: macro-oss # oss的存儲空間
    policy:
      expire: 300 # 簽名有效期(S)
    maxSize: 10 # 上傳文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上傳成功後的回調地址
    dir:
      prefix: mall/images/ # 上傳文件夾路徑前綴

minio:
  endpoint: http://localhost:9090 #MinIO服務所在地址
  bucketName: mall #存儲桶名稱
  accessKey: minioadmin #訪問的key
  secretKey: minioadmin #訪問的秘鑰
