server:
  port: 8085

spring:
  datasource:
    #url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8 
    username: root
    password: 1234
    druid:
      initial-size: 5 #連接池初始化大小
      min-idle: 10 #最小空閒連接數
      max-active: 20 #最大連接數
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不統計這些請求數據
      stat-view-servlet: #訪問監控網頁的登錄用戶名和密碼
        login-username: druid
        login-password: druid

  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port

  redis:
    host: redis # Redis服務器地址
    database: 0 # Redis數據庫索引（默認為0）
    port: 6379 # Redis服務器連接端口
    password: # Redis服務器連接密碼（默認為空）
    timeout: 300ms # 連接超時時間（毫秒）

  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /
    username: mall
    password: mall

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

logstash:
  host: localhost

