spring:
  application:
    name: mall-portal
  profiles:
    active: dev #默認為開發環境

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存儲的請求頭
  secret: mall-portal-secret #JWT加解密使用的密鑰
  expiration: 604800 #JWT的超期限時間(60*60*24*7)
  tokenHead: 'Bearer '  #JWT負載中拿到開頭

secure:
  ignored:
    urls: #安全路徑白名單
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**

# 自定義redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 驗證碼超期時間
    common: 86400 # 24小時

# 消息隊列定義
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue

