spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8 
    username: root
    password: 1234
    druid:
      initial-size: 5 #連接池初始化大小
      min-idle: 10 #最小空閒連接數
      max-active: 20 #最大連接數
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不統計這些請求數據
      stat-view-servlet: #訪問監控網頁的登錄用戶名和密碼
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: localhost:9200

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost