spring:
  application:
    name: mall-search
  profiles:
    active: dev #默認為開發環境

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



